name: Autotools using hyrax-dependencies

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        set -x
        sudo apt-get install -o Acquire::Retries=3 wget gfortran 
    - name: cache-hyrax-dependencies
      id: cache-hyrax-dependencies
      uses: actions/cache@v2
      with:
        path: ~/hyrax-dependencies
        key: hyrax-dependencies-${{ runner.os }}-1

    - name: build-hyrax-dependencies
      if: steps.cache-hyrax-dependencies.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://github.com/OPENDAP/hyrax-dependencies/archive/hyrax-1.16.2.tar.gz
        tar zxf hyrax-1.16.2.tar.gz
        ls -l
        cd hyrax-dependencies-hyrax-1.16.2
        export CXXFLAGS=-std=c++11
        export prefix=/home/runner/hyrax-dependencies
        export BUILD_STARE=1
        make -j jpeg openjpeg bison hdf4 hdfeos hdf5 netcdf4 stare
        ls -l /home/runner/hyrax-dependencies/deps
        ls -l /home/runner/hyrax-dependencies/deps/include
        ls -l /home/runner/hyrax-dependencies/deps/lib
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: |
        export CPPFLAGS=-I/home/runner/hyrax-dependencies/deps/include
        export LDFLAGS=-L/home/runner/hyrax-dependencies/deps/lib
        ./configure
        make -j distcheck


