name: Autotools ubuntu-latest HDFEOS2.19 no HDF4

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PWD_DIR: /home/runner
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/stare/include"
      LDFLAGS: "-L/home/runner/stare/lib"
        
    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        set -x
        sudo apt-get install -o Acquire::Retries=3 netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev
    - name: cache-stare
      id: cache-stare
      uses: actions/cache@v2
      with:
        path: ~/stare
        key: stare-${{ runner.os }}-0.16.3

    - name: build-stare
      if: steps.cache-stare.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://github.com/SpatioTemporal/STARE/archive/0.16.3-beta.tar.gz  &> /dev/null
        tar zxf 0.16.3-beta.tar.gz
        cd STARE-0.16.3-beta/
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/stare ..
        make all
        sudo make install
        cd ../..
        
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: |
        export CXXFLAGS=-fpermissive
        ./configure --disable-hdf4
        make -j check


